# 01. Знакомство с `torch.Tensor`

V 0.1 04.02.2021

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [4]:
import torch
from torch.nn.functional import normalize
import numpy as np

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [13]:
x = torch.zeros(8, 8)
x1 = torch.tensor([4, 3, 2, 6, 5, 2, 3, 4])
x2 = torch.ones(1, 8)
x[0] = -1 * x1
x[1] = -1 * x2
x[6] = x2
x[7] = x1; x

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

### 1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [25]:
x = torch.arange(2, 22, 2)
x1 = torch.arange(3, 23, 2)
x1*x

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [44]:
x = torch.range(1,7)
y = torch.zeros(11,7)
y[0] = x
for i in range(1, 11):
    x1 = x+10
    x = x1
    y[i] = x1

C:\Users\195238\AppData\Local\Temp/ipykernel_13996/1749972685.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  x = torch.range(1,7)


In [45]:
y

tensor([[  1.,   2.,   3.,   4.,   5.,   6.,   7.],
        [ 11.,  12.,  13.,  14.,  15.,  16.,  17.],
        [ 21.,  22.,  23.,  24.,  25.,  26.,  27.],
        [ 31.,  32.,  33.,  34.,  35.,  36.,  37.],
        [ 41.,  42.,  43.,  44.,  45.,  46.,  47.],
        [ 51.,  52.,  53.,  54.,  55.,  56.,  57.],
        [ 61.,  62.,  63.,  64.,  65.,  66.,  67.],
        [ 71.,  72.,  73.,  74.,  75.,  76.,  77.],
        [ 81.,  82.,  83.,  84.,  85.,  86.,  87.],
        [ 91.,  92.,  93.,  94.,  95.,  96.,  97.],
        [101., 102., 103., 104., 105., 106., 107.]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [38]:
def torch_gen(n,m):
    x = torch.tensor([[0, 1],
                      [2, 3]])
    concat0 = x
    for i in range(n):
        concat = torch.cat((concat0, concat0), dim = 1)
        concat0 = concat
    for j in range(m):
        concat1 = torch.cat((concat0, concat0))
        concat0 = concat1
    concat2 = torch.hsplit(concat0, [m, n])
    return concat2[0][:n]

In [42]:
torch_gen(6,3)

tensor([[0, 1, 0],
        [2, 3, 2],
        [0, 1, 0],
        [2, 3, 2],
        [0, 1, 0],
        [2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

In [62]:
x = torch.rand(4, 7)*20
x_min, x_max = x.min(), x.max()
new_min, new_max = 0, 1

In [63]:
x_p = (x - x_min)/(x_max - x_min)*(new_max - new_min) + new_min; x_p

tensor([[0.5391, 0.8317, 0.2404, 1.0000, 0.5063, 0.3574, 0.0710],
        [0.3244, 0.9768, 0.6227, 0.0821, 0.8862, 0.3172, 0.7283],
        [0.8536, 0.3754, 0.0000, 0.6388, 0.8461, 0.0740, 0.3967],
        [0.1968, 0.3955, 0.6496, 0.7910, 0.8221, 0.4510, 0.1089]])

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в массивах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [79]:
ar1 = torch.randint(0, 10, (4, 7))
ar2 = torch.randint(0, 10, (4, 7))
ar3 = torch.zeros(4, 7)
for i in range(4):
    for j in range(7):
        ar3[i][j] = torch.max(ar1[i][j], ar2[i][j])
ar3

tensor([[6., 6., 0., 7., 8., 3., 9.],
        [7., 7., 2., 1., 6., 4., 8.],
        [4., 3., 7., 9., 2., 1., 4.],
        [7., 4., 7., 9., 8., 2., 9.]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [91]:
x = torch.randint(0, 100, (1, 20))
sorted, indices = torch.sort(x[0], 0)
x, sorted, indices, indices[-2]

(tensor([[98, 89, 75, 16, 62, 23, 31, 88, 15, 17, 91, 37, 51, 83, 56, 13, 89, 16,
          83, 60]]),
 tensor([13, 15, 16, 16, 17, 23, 31, 37, 51, 56, 60, 62, 75, 83, 83, 88, 89, 89,
         91, 98]),
 tensor([15,  8,  3, 17,  9,  5,  6, 11, 12, 14, 19,  4,  2, 13, 18,  7,  1, 16,
         10,  0]),
 tensor(10))

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [96]:
tensor11_7 = torch.arange(11*7).reshape(11, 7) + torch.arange(0, 31, 3).reshape(11, 1) + 1; tensor11_7

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [103]:
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])

In [107]:
a_2d - b_1d.reshape(3, 1)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
array([1, 3, 5, 7])
```

In [108]:
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])

In [112]:
a == b

tensor([False,  True, False,  True, False,  True, False,  True, False, False])

In [110]:
x = torch.nonzero(a == b, as_tuple = True); x

(tensor([1, 3, 5, 7]),)

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [130]:
x = torch.arange(9).view(3,3)
x1 = x.reshape(-1,).sort(descending = True)[0].reshape(3,3); x1

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Ожидается резульат:

```python
array([6, 9, 10])
```

In [132]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

tensor([ 5,  6,  7,  8,  9, 10])

In [136]:
a = a[(a >= 5) & (a <= 10)]; a

tensor([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2 тензора `np.arange(9).reshape(3,3)`

In [150]:
a = torch.arange(9).reshape(3,3)
a[:, [0,2,1]]

tensor([[0, 2, 1],
        [3, 5, 4],
        [6, 8, 7]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [187]:
a = torch.randint(0, 11, size=(8, 10))
index = arr.sum(axis=1).max(axis=0).indices.item()
print(index)
print(arr[index])

0
tensor([ 0,  2, 10,  7,  6,  7,  9,  9,  8,  6])


1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [189]:
x = torch.randint(0, 100, (1, 20))
x[(x < 30)] = 30
x[(x > 70)] = 70
x

tensor([[30, 70, 35, 56, 30, 70, 30, 45, 44, 30, 30, 69, 32, 70, 70, 30, 39, 30,
         43, 43]])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [190]:
x1 = torch.randint(0, 11, size=(30, 3))
x2 = torch.randint(0, 11, size=(30, 3))

In [193]:
print(x1[x1 > x2])
print(x1[x1 > x2].sum())

tensor([ 6,  8,  2,  6,  5,  3,  5,  4,  4,  7,  7, 10,  9,  6,  5,  7,  3,  7,
         8,  3, 10,  4,  9,  2,  5,  6, 10, 10,  2,  6,  8,  9,  5,  1,  8,  6,
         9,  5,  4])
tensor(234)


1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [194]:
x = torch.randint(0, 11, size=(20, 20)); x

tensor([[ 4,  5,  4,  8,  0,  1, 10,  9,  4,  1,  6,  8,  5,  0, 10,  8,  3,  0,
          8,  6],
        [10,  5,  1,  0,  7,  3,  6,  3,  2,  1,  3,  8,  5,  7,  8, 10,  0,  8,
          9,  1],
        [ 0, 10,  5,  8,  1,  0,  2,  9,  7,  5,  0,  9,  7, 10,  2,  7,  3,  2,
          3,  0],
        [ 8,  1,  5,  0,  1,  4,  5,  7,  4,  9,  2,  5, 10,  0,  3,  3,  0,  1,
          0,  7],
        [ 9,  4, 10,  4,  7,  5,  9,  1,  7,  8,  5,  1,  3,  0, 10,  8, 10,  4,
          0,  2],
        [ 9,  7,  6,  6,  9,  3,  7,  3,  3,  7,  4,  0,  5,  6,  6,  5,  9,  7,
          3, 10],
        [ 1,  0,  9,  5,  3,  7,  7,  5,  0, 10,  3,  1,  4,  0,  9,  2, 10,  7,
          3,  6],
        [ 8,  6,  3,  5,  7,  8, 10,  5,  7,  6,  8,  3,  6, 10,  5,  7,  6,  7,
          4,  1],
        [ 5, 10,  2,  0,  2,  9,  9,  0,  0, 10,  4,  0,  5,  9,  2,  4,  0,  2,
          2,  3],
        [ 4,  9,  2,  2,  1,  0,  1,  0,  7,  9,  7,  8,  3,  4,  3,  3,  1,  8,
          4,  6],
        [1

In [198]:
print(x[torch.arange(19), torch.arange(19) + 1])

tensor([ 5,  1,  8,  1,  5,  7,  5,  7, 10,  7,  1,  0,  8,  2,  2,  6,  3,  0,
         3])


1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [196]:
x1 = torch.randint(0, 11, size=(5, 10))
x2 = torch.randint(0, 11, size=(5, 10))
arr1[x1 == x2] *= 2; x1

tensor([[ 0, 10,  8,  8,  5,  8,  5,  3,  5,  7],
        [ 6,  8,  8,  5,  3,  9,  2,  7,  9,  5],
        [ 2,  1,  0,  9,  9,  5,  5,  8, 10,  5],
        [ 6,  1,  6,  3,  5,  2,  1,  4,  6,  3],
        [ 1,  3,  6,  1,  9,  7,  3,  9,  2,  6]])
tensor([[ 4,  6, 10, 10,  2, 10, 10, 10,  4,  3],
        [ 5,  9,  8,  5,  2,  7,  7,  4,  8,  6],
        [ 1,  5,  4,  4,  0,  1,  6,  4,  7,  9],
        [ 6,  4,  6,  9,  4,  9, 10,  5,  0, 10],
        [ 8,  3,  5,  4,  3,  0,  5,  5,  9,  1]])


tensor([[ 0, 10,  8,  8,  5,  8,  5,  3,  5,  7],
        [ 6,  8, 16, 10,  3,  9,  2,  7,  9,  5],
        [ 2,  1,  0,  9,  9,  5,  5,  8, 10,  5],
        [12,  1, 12,  3,  5,  2,  1,  4,  6,  3],
        [ 1,  6,  6,  1,  9,  7,  3,  9,  2,  6]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [199]:
x1 = torch.randint(0, 11, size=(4, 7))
x2 = torch.randint(0, 11, size=(4, 7))
x3 = torch.randint(0, 11, size=(4, 7))

In [200]:
x1[(x1 > x2) & (x1 < x3)] = 0
x1

tensor([[ 0,  1,  9,  4,  5,  3,  8],
        [ 6,  8,  1,  9, 10,  2,  3],
        [ 3,  1, 10,  0,  7,  5,  5],
        [ 4,  0,  0,  1,  0, 10,  0]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [201]:
x1 = torch.randint(0, 21, size=(20, 5)); x1

tensor([[ 6, 17, 10,  1,  8],
        [19,  1, 15, 13, 15],
        [17,  3,  7,  6,  0],
        [ 7, 17,  4,  7,  0],
        [ 1, 20,  7,  4, 15],
        [19,  0,  3,  2, 18],
        [12,  8, 19, 14, 16],
        [16,  0, 16,  1,  3],
        [ 6, 14,  7,  2,  5],
        [16,  1,  7,  2,  4],
        [13,  1,  9,  2, 10],
        [17,  6,  9,  9, 14],
        [ 6, 12,  2, 10, 12],
        [ 3, 13,  0, 10, 14],
        [14, 12,  7, 11, 18],
        [ 5,  2, 17, 15, 20],
        [ 5,  9, 15, 12, 15],
        [20,  5, 12, 16,  3],
        [10, 13, 16, 14,  4],
        [ 4, 14, 18, 17,  9]])

1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива. 

In [224]:
ar1 = torch.rand((4, 7))
maximum = ar1.max().item()
ar1[(ar1 == maximum).nonzero(as_tuple=True)[0][0] + 1:, (ar1 == maximum).nonzero(as_tuple=True)[1][0] + 1:] = 0; ar1

tensor([[0.2620, 0.3031, 0.0056, 0.5875, 0.0898, 0.8112, 0.1211],
        [0.0480, 0.1881, 0.8274, 0.8439, 0.0043, 0.3481, 0.1123],
        [0.0247, 0.4352, 0.2191, 0.8919, 0.3819, 0.1573, 0.1550],
        [0.1170, 0.6764, 0.7433, 0.6477, 0.0000, 0.0000, 0.0000]])

In [225]:
(ar1 == maximum).nonzero(as_tuple=True)[1][0]

tensor(3)

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

In [240]:
x = torch.tensor([2, 4, 2, 5, 2, 1])
encoding = torch.zeros(x.size()[0], vec.max())
encoding[torch.arange(x.size()[0]), x-1] = 1
encoding

tensor([[0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая. 

## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [244]:
n = 1000
x = torch.linspace(0, 10, n)
((x * torch.sin(x)) > 0.5).sum()/n

tensor(0.5230)

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [259]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
y = torch.tensor([2, 3, 4, 5, 6, 7, 8, 9, 10])

print(np.sqrt(((x - y) ** 2).sum().item()))

3.0


1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

In [264]:
x = torch.randint(0, 101, size=(20, 3))
print(x[np.sqrt((x ** 2).sum(axis=1)).sort().indices])

tensor([[ 57,  16,  17],
        [ 58,  19,  17],
        [  0,  61,  22],
        [ 10,  55,  51],
        [ 59,  41,  30],
        [  3,  78,   0],
        [ 34,  63,  35],
        [  3,  55,  61],
        [  5,  34,  76],
        [ 17,  52,  66],
        [ 74,  40,  46],
        [ 72,  47,  47],
        [ 97,   0,  23],
        [ 67,   3,  75],
        [ 59,  80,  35],
        [ 82,  39,  58],
        [ 64,  83,  28],
        [ 87,  64,  34],
        [100,  53,  17],
        [ 92,  18,  88]])


1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

In [270]:
vec = torch.tensor([1, 3, 7, 10, 2, 6, 10, 1])
a = torch.diff(vec)[:-1]
b = torch.diff(vec.flip(0)).flip(0)[1:]
print(a, b)

tensor([ 2,  4,  3, -8,  4,  4]) tensor([-4, -3,  8, -4, -4,  9])


In [280]:
print(((a > 0) & (b > 0)).nonzero(as_tuple=True))

(tensor([2, 5]),)


1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 