In [1]:
import torch

## 2.1 Создание нейронов и полносвязных слоев

2.1.1. Используя операции над матрицами и векторами из библиотеки `torch`, реализовать нейрон с заданными весами `weights` и `bias`. Прогнать вектор `inputs` через нейрон и вывести результат. 

In [ ]:
class Neuron:
      def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
        pass

      def forward(self, inputs):
        output = torch.dot(weights, inputs) + self.bias    
        return output

In [ ]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
bias = 3.14
neu = Neuron(weights, bias)

In [ ]:
neu.forward(inputs)

tensor(4.8400)

2.1.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой с заданными весами `weights` и `biases`. Прогнать вектор `inputs` через слой и вывести результат. 

In [ ]:
class Linear:
      def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
        pass

      def forward(self, inputs):
        output = torch.matmul(inputs, weights) + self.biases
        return output

In [ ]:
inputs = torch.tensor([[1.0, 2.0, 3.0, 4.0]])
weights = torch.tensor([[-0.2, 0.3, -0.5, 0.7],
                        [0.5, -0.91, 0.26, -0.5],
                        [-0.26, -0.27, 0.17, 0.87]]).T

biases = torch.tensor([3.14, 2.71, 7.2])

In [ ]:
neu = Linear(weights, bias)
neu.forward(inputs)

tensor([[ 2.9400,  3.2100,  6.9400],
        [ 3.7400,  0.8900,  6.6600],
        [ 1.6400,  3.4900,  7.7100],
        [ 5.9400,  0.7100, 10.6800]])

2.1.3 Реализовать полносвязный слой из __2.1.2__ таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. Продемонстрировать работу.
Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.


In [ ]:
class Linear:
      def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias

      def forward(self, inputs):
        output = torch.matmul(inputs, weights) + self.biases
        return output

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

In [ ]:
neu = Linear(weights, bias)
neu.forward(inputs)

tensor([[ 2.9400,  3.7100,  7.5900],
        [ 3.7400, -1.8400,  6.4710],
        [ 1.6400,  2.4500,  7.7610],
        [ 4.8900,  1.7100,  6.5040]])

2.1.4 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения). Прогнать вектор `inputs` через слой и вывести результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

In [ ]:
class Linear:
      def __init__(self, n_features, n_neurons):
        self.w = torch.randn(n_neurons, n_features)
        self.b = torch.randn(n_neurons)
        pass

      def forward(self, inputs):
        return torch.matmul(inputs, self.w) + self.b

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

n_neurons, n_features = 5, 4

nn_4 = Linear(n_features, n_neurons).forward(inputs); nn_4

tensor([[ 7.2674,  4.9830, -7.7018, -0.4211, -5.2151],
        [ 2.0390,  4.8124, -1.6678,  3.2246, -8.1055],
        [ 5.1547, -0.6974, -3.5237, -2.4117, -6.5945]])

2.1.5 Используя решение из __2.1.4__, создать 2 полносвязных слоя и пропустить матрицу `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выбрать произвольно, количество нейронов во втором слое выбрать так, чтобы результатом прогона являлась матрица (3x7). 

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

In [ ]:
a, b = Linear(4, 3), Linear(3, 7)
b.forward(a.forward(inputs))

tensor([[ 3.3834, -5.4573,  0.9270, -3.1700, -3.5572, -0.5477,  1.9104],
        [ 4.4967, -6.5501,  6.2990, -5.3863,  4.5801,  1.0482,  1.9520],
        [ 3.2120, -6.7175, -3.0371, -1.3277, -8.9775, -1.1923,  1.2636]])

## 2.2 Создание функций активации

2.2.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [ ]:
from torch.nn import ReLU

In [ ]:
class ReLU1:
    def forward(self, inputs):
        self.inputs = inputs
        inputs[(inputs < 0)] = 0
        return inputs

In [ ]:
m = ReLU1()

In [ ]:
inputi = torch.randn(4, 3); inputi

tensor([[ 1.3268,  1.5782, -0.7202],
        [-0.6921, -0.4556,  1.4412],
        [-0.0512,  0.6448, -0.6462],
        [ 0.2759,  0.5214, -3.6641]])

In [ ]:
output = m.forward(inputi); output

tensor([[1.3296, 0.1498, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 2.0738, 0.0000],
        [0.9025, 0.0000, 0.0000]])

2.2.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров.

In [ ]:
from torch.nn import Softmax

In [ ]:
m = Softmax()

In [ ]:
output = m(inputi); output

C:\Users\nabr9\AppData\Local\Temp/ipykernel_13720/1256584602.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output = m(inputi); output


tensor([[0.4358, 0.2205, 0.3437],
        [0.8322, 0.1303, 0.0375],
        [0.5710, 0.3539, 0.0751],
        [0.1682, 0.1623, 0.6695]])

In [5]:
class Softmax:
      def forward(self, inputs):
        self.inputs = inputs
        exponential = torch.exp(inputs)
        probabilities = exponential.T / torch.sum(exponential, 1)
        return probabilities.T

In [ ]:
Softmax().forward(inputi)

tensor([[0.0641, 0.1744, 0.4740, 0.2875],
        [0.0452, 0.9074, 0.0022, 0.0452],
        [0.0052, 0.3488, 0.6355, 0.0105]])

2.2.3 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [ ]:
from torch.nn import ELU

In [ ]:
m = ELU()

In [ ]:
m(inputi)

tensor([[ 0.4925, -0.1721,  0.2553],
        [ 1.2305, -0.4643, -0.8458],
        [ 0.0668, -0.3374, -0.8593],
        [-0.3394, -0.3627,  0.9669]])

In [ ]:
import math

In [ ]:
class ELU:
    def __init__(self, alpha):
        self.alpha = alpha

    def forward(self, inputs):
        d = inputs[(inputs < 0)]
        c = torch.zeros_like(d)
        c = self.alpha*(torch.exp(d) - 1)
        inputs[(inputs < 0)] = c
        return inputs
    

In [ ]:
ELU(1).forward(inputi)

tensor([[ 1.3268,  1.5782, -0.5134],
        [-0.4995, -0.3659,  1.4412],
        [-0.0499,  0.6448, -0.4759],
        [ 0.2759,  0.5214, -0.9744]])

## 2.3 Создание функции потерь

2.3.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)

Создать полносвязный слой с 1 нейроном, прогнать через него батч `inputs` и посчитать значение MSE, трактуя вектор `y` как вектор правильных ответов.

In [ ]:
class MSELoss:
      def forward(self, y_true, y_pred):
        diff = y_pred - y_true
        differences_squared = diff ** 2 
        mean_diff = torch.mean(differences_squared)
        return mean_diff.item()

In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

y = torch.tensor([2, 3, 4])

In [ ]:
n_neurons = 1
nn = Linear(inputs.shape[1], n_neurons)
y_p = nn.forward(inputs)
mse = MSELoss()
mse.forward(y, y_p)

24.164337158203125

In [ ]:
MSELoss().forward(y_true = y, n_features = n_features, n_neurons = n_neurons, inputs = inputs)

12.111837387084961

In [ ]:
#???

2.3.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь Categorical Cross-Entropy:

<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

Создать полносвязный слой с 3 нейронами и прогнать через него батч `inputs`. Полученный результат пропустить через функцию активации softmax. Посчитать значение CCE, трактуя вектор `y` как вектор правильных ответов.

In [2]:
class CategoricalCrossentropyLoss:
        def forward(self, y_true, y_pred):
            y_log = torch.log(y_pred)
            res = y_log.gather(dim = 1, index = y_true.view(-1, 1).type(torch.int64))
            return -(torch.sum(res))

In [3]:
inputi = torch.tensor([[1, 2, 3, 2.5], 
                        [2, 5, -1, 2], 
                        [-1.5, 2.7, 3.3, -0.8]])
y = torch.tensor([1, 0, 0])

In [6]:
m = Softmax()
y_p = Softmax().forward(inputi)

In [7]:
n = CategoricalCrossentropyLoss()
d = n.forward(y, y_p); d

tensor(10.0971)

2.3.3 Модифицировать 2.3.1, добавив L2-регуляризацию.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/d92ca2429275bfdc0474523babbafe014ca8b580)


In [ ]:
class MSELossL2:
  def __init__(self, lambda_):
    self.lambda_ = lambda_

  def data_loss(self, y_pred, y_true):
    return torch.sum((y_true - y_pred)**2)

  def reg_loss(self, layer):
    return self.lambda_*(torch.sum(layer**2))

  def forward(self, y_pred, y_true):
    return self.data_loss(y_pred, y_true) + self.reg_loss(y_pred, y_true)

## 2.4 Обратное распространение ошибки

2.4.1 Используя один нейрон и SGD (1 пример за шаг), решите задачу регрессии

In [10]:
from sklearn.datasets import make_regression

X, y, coef = make_regression(n_features=4, n_informative=4, coef=True, bias=0.5)
X = torch.tensor(X, dtype = torch.float)
y = torch.tensor(y, dtype = torch.float)
print(X, y, X.size())

tensor([[ 7.6780e-01, -6.8620e-01,  1.2631e+00, -2.8872e-01],
        [-1.7734e+00,  1.1224e+00, -8.8477e-01, -1.4543e-01],
        [-1.2609e+00, -1.5720e+00,  1.9641e+00, -6.6260e-01],
        [ 6.0457e-01,  1.1431e-02,  4.2441e-01,  1.1050e+00],
        [-2.5719e-01,  1.8615e+00, -1.4998e-01, -1.0188e-01],
        [ 1.1408e+00, -1.2100e-02, -2.3553e-02,  1.3068e-01],
        [ 1.4180e-01,  1.1271e+00, -4.1172e-02, -1.2714e+00],
        [ 1.9371e+00,  1.7808e+00, -6.9528e-01, -2.1304e-01],
        [ 2.9651e-02, -2.3654e-01, -1.0546e-01, -1.8394e-01],
        [ 1.2465e+00, -8.9073e-01, -3.5347e-01,  8.1038e-01],
        [-1.3281e+00, -7.2703e-01, -1.4838e+00,  7.6372e-02],
        [-1.1437e+00,  9.4183e-01, -3.3054e-01,  1.5276e+00],
        [ 5.9651e-01, -7.3723e-02,  2.4682e-01, -1.4206e+00],
        [-9.1149e-02,  3.4789e-01, -1.6677e+00, -1.3477e-01],
        [-1.1009e+00,  1.1292e+00, -7.5064e-01,  4.1360e-01],
        [-3.2711e-01,  7.2586e-01, -1.1065e-02, -1.5242e+00],
        

[Граф вычислений для этой задачи](https://i.ibb.co/2dhDxZx/photo-2021-02-15-17-18-04.jpg)

2.4.1.1 Реализуйте класс `SquaredLoss`


In [54]:
class SquaredLoss:
  def forward(self, y_pred, y_true):
    return torch.mean(torch.sum((y_true - y_pred)**2))

  def backward(self, y_pred, y_true):
    self.dinput = ((2* (y_pred - y_true)))


2.4.1.2. Модифицируйте класс `Neuron` из __2.1.1__:

  1) Сделайте так, чтобы веса нейрона инициализировались из стандартного нормального распределения

  2) Реализуйте расчет градиента относительно весов `weights` и `bias`

In [51]:
class Neuron:
  def __init__(self, n_inputs):
    # <создать атрибуты объекта weights и bias>
    self.weights = torch.randn(n_inputs, 1)
    self.bias = torch.randn(1)
  
  def forward(self, inputs):
    self.inputs = inputs
    res = torch.matmul(inputs, self.weights) + self.bias
    return res
  
  def backward(self, dvalue):
    # dvalue - значение производной, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет значение df/dc (созданное методом backwards у объекта MSELoss)
    self.dweights = (self.inputs*dvalue).unsqueeze(1)
    self.dinput =  dvalue*self.weights
    self.dbias = torch.mean(dvalue, dim=0)


2.4.1.3 Допишите цикл для настройки весов нейрона

[SGD](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%BE%D1%85%D0%B0%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%81%D0%BA)

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/dda3670f8a8996a0d3bf80856bb4a166cc8db6d4)

In [55]:
n_inputs = 4 # <размерность элемента выборки >
learning_rate = 0.1 #  скорость обучения
n_epoch = 100 #  количество эпох

neuron = Neuron(n_inputs)
loss = SquaredLoss()

losses = []
for epoch in range(100):
  for x, yy in zip(X, y):
    y_pred = neuron.forward(x)
    curr_loss = loss.forward(y_pred, yy)
    losses.append(curr_loss)

    # backprop
    # <вызов методов backward>
    loss.backward(y_pred, yy)
    neuron.backward(loss.dinput)
    # <шаг оптимизации для весов (weights и bias) нейрона>
    neuron.weights -= learning_rate * neuron.dweights
    neuron.bias -= learning_rate * neuron.dbias
  print('эпоха', epoch, curr_loss)

эпоха 0 tensor(0.0326)
эпоха 1 tensor(1.8859e-08)
эпоха 2 tensor(2.3283e-10)
эпоха 3 tensor(1.3097e-10)
эпоха 4 tensor(2.3283e-10)
эпоха 5 tensor(2.3283e-10)
эпоха 6 tensor(2.3283e-10)
эпоха 7 tensor(2.3283e-10)
эпоха 8 tensor(2.3283e-10)
эпоха 9 tensor(2.3283e-10)
эпоха 10 tensor(2.3283e-10)
эпоха 11 tensor(2.3283e-10)
эпоха 12 tensor(2.3283e-10)
эпоха 13 tensor(2.3283e-10)
эпоха 14 tensor(2.3283e-10)
эпоха 15 tensor(2.3283e-10)
эпоха 16 tensor(2.3283e-10)
эпоха 17 tensor(2.3283e-10)
эпоха 18 tensor(2.3283e-10)
эпоха 19 tensor(2.3283e-10)
эпоха 20 tensor(2.3283e-10)
эпоха 21 tensor(2.3283e-10)
эпоха 22 tensor(2.3283e-10)
эпоха 23 tensor(2.3283e-10)
эпоха 24 tensor(2.3283e-10)
эпоха 25 tensor(2.3283e-10)
эпоха 26 tensor(2.3283e-10)
эпоха 27 tensor(2.3283e-10)
эпоха 28 tensor(2.3283e-10)
эпоха 29 tensor(2.3283e-10)
эпоха 30 tensor(2.3283e-10)
эпоха 31 tensor(2.3283e-10)
эпоха 32 tensor(2.3283e-10)
эпоха 33 tensor(2.3283e-10)
эпоха 34 tensor(2.3283e-10)
эпоха 35 tensor(2.3283e-10)
эпоха 

2.4.2 Решите задачу 2.4.1, используя пакетный градиентный спуск

Вычисления для этой задачи: 
[1](https://i.ibb.co/rmtQT6P/photo-2021-02-15-18-00-43.jpg)
[2](https://i.ibb.co/NmCFVnQ/photo-2021-02-15-18-01-17.jpg)

2.4.1.1 Модифицируйте класс `MSELoss` из __2.3.1__, реализовав расчет производной относительно предыдущего слоя с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами
 

In [ ]:
class MSELoss:
  def forward(self, y_pred, y_true):
    return # <реализовать логику MSE>

  def backward(self, y_pred, y_true):
    self.dinput = # df/dy^


2.4.2.2. Модифицируйте класс `Neuron` из __2.4.1.2__:

  1) Реализуйте метод `forward` таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. 

  2) Реализуйте расчет градиента относительно весов `weights` и `bias` с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами

In [ ]:
class Neuron:
  def __init__(self, n_inputs):
    # <создать атрибуты объекта weights и bias>
    pass
  
  def forward(self, inputs):
    return # <реализовать логику нейрона>
  
  def backward(self, dvalue):
    # dvalue - значение градиента, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет градиент L по y^ (созданный методом backwards у объекта MSELoss)
    self.dweights = # df/dW
    self.dbias = # df/db


2.4.2.3 Допишите цикл для настройки весов нейрона

In [ ]:
n_inputs = 100 # <размерность элемента выборки >
learning_rate = 0.1 #  скорость обучения
n_epoch = 100 #  количество эпох

neuron = Neuron(n_inputs)
loss = MSELoss()


for epoch in range(100):
    # forward pass
    y_pred = # <прогон через нейрон>
    curr_loss = # <прогон через функцию потерь>
    losses.append(curr_loss)

    # backprop
    # <вызов методов backward>
    # обратите внимание на последовательность вызовов: от конца к началу

    # <шаг оптимизации для весов (weights и bias) нейрона>

2.4.3  Используя один полносвязный слой и  пакетный градиетный спуск, решите задачу регрессии из __2.4.1__

2.4.3.1 Модифицируйте класс `Linear` из __2.1.4__. ([вычисление градиентов](https://i.ibb.co/kgVR6m6/photo-2021-02-15-21-30-28.jpg))

In [ ]:
class Linear:
  def __init__(self, n_features, n_neurons):
    # <создать атрибуты объекта weights и biases>
    pass
  
  def forward(self, inputs):
    return # <реализовать логику слоя>

  def backward(self, dvalues):
    self.dweights = # df/dW
    self.dbiases = # df/db
    self.dinputs = # df/dX

2.4.3.2 Создайте слой с одним нейроном. Используя класс MSELoss из 2.4.2, убедитесь, что модель обучается

2.4.4 Используя наработки из 2.4, создайте нейросеть и решите задачу регрессии.

Предлагаемая архитектура: 
1. Полносвязный слой с 10 нейронами
2. Активация ReLU
3. Полносвязный слой с 1 нейроном

In [ ]:
X = torch.linspace(-1, 1, 100).view(-1, 1)
y = X.pow(2) + 0.2 * torch.rand(X.size()) 

In [ ]:
class Activation_ReLU:
  def forward(self, inputs):
    self.inputs = inputs
    self.output = inputs.clip(min=0)
    return self.output
  
  def backward(self, dvalues):
    self.dinputs = dvalues.clone()
    self.dinputs[self.inputs <= 0] = 0

In [ ]:
# создание компонентов сети
# fc1 = 
# relu1 = 
# fc2 = 

loss = MSELoss()
lr = 0.02

ys = []
for epoch in range(2001):
  # <forward pass>
  # fc1 > relu1 > fc2 > loss

  data_loss = # <прогон через функцию потерь>

  if epoch % 200 == 0:
    print(f'epoch {epoch} mean loss {data_loss}')
    ys.append(out)
  
  # <backprop> 
  # loss > fc2 > relu1 > fc1

  # <шаг оптимизации для fc1>

  # <шаг оптимизации для fc2>


In [ ]:
import matplotlib.pyplot as plt

fig, axs = plt.subplots(len(ys), 1, figsize=(10, 40))
for ax, y_ in zip(axs, ys):
  ax.scatter(X.numpy(), y.numpy(), color = "orange")
  ax.plot(X.numpy(), y_.numpy(), 'g-', lw=3)
  ax.set_xlim(-1.05, 1.5)
  ax.set_ylim(-0.25, 1.25)