# Введение в обучение искуcственных нейронных сетей

Материалы:
* Макрушин С.В. "Лекция 6: Введение в обучение искуcственных нейронных сетей и сверточные нейронные сети"
* Документация:
    * https://pytorch.org/docs/stable/index.html
    * https://pytorch.org/docs/stable/nn.html
    * https://pytorch.org/docs/stable/optim.html
    * https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_regression.html

In [1]:
import torch

In [2]:
x = torch.empty(1); x

tensor([1.4013e-45])

## Тензоры

1.1 Загрузить датасет `diabetes` из `sklearn` и представить его в виде тензоров `torch`. Вывести основные характеристики тензоров: размерность, тип, устройство.

1.2 Сгенерировать трехмерный тензор `I`, имитирующий картинку в формате RGB. Размерность вектора: 3x200x200. Значения: интенсивность пикселя (от 0 до 255). Разбить тензор `T` на три двумерных тензора `R`, `G`, и `B`.

In [15]:
I = torch.randint (0, 255, (3, 200, 200))
for i in I:
    print(i)

tensor([[ 95,  44, 138,  ...,  91, 140, 107],
        [157,  93, 104,  ..., 106,  40, 125],
        [ 32,  87, 243,  ..., 181,  26,  96],
        ...,
        [224, 109, 166,  ...,  91,  65,  95],
        [ 48,  83,  39,  ...,  47,  72, 226],
        [251,  64,  41,  ..., 253, 145,   4]])
tensor([[186,  58, 231,  ...,   3, 170,  37],
        [ 23,  33, 216,  ..., 167,  10, 212],
        [ 89, 103,  73,  ..., 189, 160,  96],
        ...,
        [  6,  33,  12,  ..., 108,  84,   7],
        [ 37, 156,  27,  ..., 142,  52, 199],
        [109, 109, 153,  ..., 201, 225,  34]])
tensor([[ 19, 206, 239,  ...,  16, 244, 159],
        [ 98, 121,  92,  ...,  59,  76,  92],
        [ 30,  76,   1,  ...,  32, 189,  73],
        ...,
        [ 84, 216, 246,  ...,   1, 208,  25],
        [149, 209,  33,  ..., 216,  74, 247],
        [ 23,   1, 157,  ...,  98,  73, 105]])


1.3 Создать двумерный тензор размера 8х8, заполненный числами из стандартного нормального распределения. Написать функцию, которая принимает на вход тензор и возвращает его копию, в которой все отрицательные числа заменены на ноль.

In [36]:
x = torch.randn(8, 8)
print( x.dim(),  x.type(), x.numel() )   # размерность, тип элементов, их количество
print( x.size(), x.shape )
x.size()[0]

2 torch.FloatTensor 64
torch.Size([8, 8]) torch.Size([8, 8])


8

In [37]:
def change_nigativ(tensor):
    I = torch.zeros_like(tensor)
    I1 = torch.where(tensor>0, tensor, I)
    return I1
            

In [38]:
# I = torch.randn(2, 3)
# for i in I:
#     for j in i:
#         if j<0:
#             j = 0
# print(I)

In [39]:
change_nigativ(x)

tensor([[0.0953, 0.2011, 0.3385, 1.1806, 0.0000, 0.0000, 0.0000, 0.9113],
        [0.2216, 0.0000, 0.7760, 0.0000, 0.0000, 0.0000, 0.2295, 0.5694],
        [1.7501, 0.0000, 0.0000, 0.0549, 0.0000, 0.0000, 0.5871, 0.0000],
        [0.0000, 0.8875, 0.6712, 0.0000, 0.7832, 0.0000, 0.0000, 1.2533],
        [0.0000, 0.6467, 0.2094, 0.6373, 0.0000, 0.0000, 0.7468, 0.0000],
        [0.0000, 2.0264, 0.0000, 0.0000, 1.1094, 0.0000, 0.0000, 0.0000],
        [1.5528, 1.2676, 0.0000, 0.0000, 0.0000, 0.0000, 0.7228, 0.0346],
        [0.0000, 0.0000, 0.6556, 0.5818, 0.2805, 1.4293, 0.0000, 0.0000]])

## 2. Автоматическое дифференцирование

2.1 Пусть $z=||XW-Y||_F^2$. Известно, что $\nabla_Wz = 2X^T(XW-Y)$. Создайте тензоры `X`, `W` и `Y` подходящих размеров и вычислите значение $\nabla_Wz$.

2.2 Вычислите значение $\nabla_Wz$ для тех же значений `X`, `W` и `Y`, воспользовавшись автоматическим дифференцированием `torch`. Сравните результаты.

# 3. Обучение нейронных сетей

3.1 При помощи функции `sklearn.dataset.make_regression` создать 2 тензора `X` и `y` типа `torch.float32` (значение параметра `noise` задайте равным 2). Разбить набор данных на обучающую и тестовую выборку в соотношении 80% на 20%. Решить задачу регрессии, воспользовавшись однослойной нейронной сетью. Оценить качество модели на обучающей и тестовой выборках, рассчитав показатель $R^2$. Сравните веса обученного слоя и истинные значения коэффициентов в модели.

3.2. Загрузите датасет из файла `3.2.csv`. Решите задачу 3.1, используя данных датасет. Добейтесь улучшения качества предсказания на счет использования многослойной нейронной сети.